apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitbash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitbash
  template:
    metadata:
      labels:
        app: gitbash
    spec:
      spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: gitbash
          image: ghcr.io/unilfc/gitbash:0.3  # Your Docker image
          ports:
            - containerPort: 80  # Change to your desired port
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"