apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-service
  template:
    metadata:
      labels:
        app: git-service
    spec:
      serviceAccountName: git-service-account
      imagePullSecrets:
        - name: ghcr-secret 
      containers:
        - name: git-service
          image: ghcr.io/unilfc/git-service:0.5
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"