apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-go-service-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: git-service-account
  namespace: default 
roleRef:
  kind: Role
  name: git-service-role
  apiGroup: rbac.authorization.k8s.io